---
owner: obrienafc
repo: ROB_Uptime
sites:
  - name: CPD Portal
    url: https://cpd.rodyobrien.com
  - name: Content Delivery Network
    url: https://cdn.rodyobrien.com
    icon: https://cdn.rodyobrien.com/images/2025-rebrand-logo.png
  - name: Mailer
    url: https://mailer.rodyobrien.com
  - name: Infomaniak KSuite
    url: https://ksuite.infomaniak.com
    icon: https://cdn.rodyobrien.com/images/kSuite.png
status-website:
  cname: status.rodyobrien.com
  logoUrl: https://cdn.rodyobrien.com/images/2025-rebrand-logo.png
  themeUrl: https://cdn.rodyobrien.com/web/status.css
  name: Rody O'Brien Legal Education Status
  favicon: https://cdn.rodyobrien.com/images/2025-rebrand-logo.png
  introTitle: Welcome to our status page.
  introMessage: This is your go-to source for real-time updates on the performance
    and uptime of our services. **Looking for help?** If you are experiencing an
    issue not listed on this page, please reach out to our support team directly
    at info@rodyobrien.com.
  navbar:
    - title: Status
      href: /
    - title: Contact us
      href: mailto:info@rodyobrien.com
i18n:
  footer: Copyright © 2026 Rody O'Brien Legal Education. This page is powered by
    [Upptime](https://upptime.js.org).
